# frozen_string_literal: true

ruby '3.0.0'

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'pg', '~> 1.2'
gem 'rack', '~> 2.2'
gem 'webrick', '~> 1.7'
