name: schedule

on:
  schedule:
    # 日本時間で毎晩 21 時
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: asdf-vm/actions/install@v1
    - run: ./bin/test.sh
